// <auto-generated />
namespace TaskModule_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ss12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ss12));
        
        string IMigrationMetadata.Id
        {
            get { return "202103201022330_ss12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
